{
 "title": "Demo_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": "SHOW TAG VALUES FROM \"demodb\" WITH KEY=\"project\""
   },
   {
    "name": "suite",
    "label": "suite",
    "query": "SHOW TAG VALUES FROM \"demodb\" WITH KEY=\"suite\""
   },
   {
    "name": "build",
    "label": "build",
    "query": "SHOW TAG VALUES FROM \"demodb\" WITH KEY=\"build\""
   },
   {
    "name": "page",
    "label": "page",
    "query": "SHOW TAG VALUES FROM \"demodb\" WITH KEY=\"page\""
   },
   {
    "name": "metric",
    "label": "metric",
    "query": "SHOW TAG VALUES FROM \"demodb\" WITH KEY=\"metric\""
   },
   { "name": "send_interval", "query": "${VAR_SEND_INTERVAL}" }
  ]
 },
 "panels": [
  { "title": "Overall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb.test",
     "query": "SELECT last(\"value\") FROM \"demodb\" WHERE (\"thread\" = 'maxAT') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "thread", "operator": "=", "value": "maxAT" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "de",
     "query": "SELECT sum(\"value\") FROM \"demodb\" WHERE (\"metric\" = 'count' AND \"status\" = 'a' AND \"page\" != 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "a" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Total Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "query": "SELECT sum(\"value\") FROM \"demodb\" WHERE (\"metric\" = 'count' AND \"status\" = 'ko' AND \"page\" != 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Error %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"error\") / sum(\"all\")  FROM (SELECT sum(\"value\") AS \"all\" FROM \"demodb\" WHERE (\"metric\" = 'count' AND \"status\" = 'a' AND \"page\" != 'all') AND $timeFilter GROUP BY time($__interval) fill(null) ),(SELECT sum(\"value\") AS \"error\" FROM \"demodb\" WHERE (\"metric\" = 'count' AND \"status\" = 'ko' AND \"page\" != 'all') AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "a" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Total throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "query": "SELECT mean(\"value\") FROM \"jmeter\" WHERE (\"build\" =~ /^$build$/ AND \"project\" =~ /^$project$/ AND \"suite\" =~ /^$suite$/ AND \"status\" = 'a' AND \"metric\" = 'count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "build", "operator": "=~", "value": "/^$build$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "suite", "operator": "=~", "value": "/^$suite$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "a" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "count" }
     ]
    }
   ]
  },
  {
   "title": "Total PASS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Overall Response Time (90 pct)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "query": "SELECT count(\"value\") FROM \"jmeter\" WHERE (\"project\" =~ /^$project$/ AND \"suite\" =~ /^$suite$/ AND \"build\" =~ /^$build$/ AND \"metric\" = 'count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "suite", "operator": "=~", "value": "/^$suite$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$build$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pct90" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "a" }
     ]
    }
   ]
  },
  { "title": "$page statstics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$page FAIL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$build$/" },
      { "condition": "AND", "key": "suite", "operator": "=~", "value": "/^$suite$/" }
     ]
    }
   ]
  },
  {
   "title": "$page PASS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "query": "SELECT sum(\"value\") FROM \"demodb\" WHERE (\"metric\" = 'count' AND \"status\" = 'ok' AND \"page\" =~ /^$page$/ AND \"project\" =~ /^$project$/ AND \"build\" =~ /^$build$/ AND \"suite\" =~ /^$suite$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$build$/" },
      { "condition": "AND", "key": "suite", "operator": "=~", "value": "/^$suite$/" }
     ]
    }
   ]
  },
  {
   "title": "$page  Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$page",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "build", "operator": "=~", "value": "/^$build$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "a" }
     ]
    }
   ]
  },
  {
   "title": "$page 90 Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$page",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "demodb",
     "query": "SELECT mean(\"value\") FROM \"jmeter\" WHERE (\"page\" =~ /^$page$/ AND \"metric\" = 'pct90' AND \"status\" = 'a' AND \"build\" =~ /^$build$/ AND \"suite\" =~ /^$suite$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pct90" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "a" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$build$/" },
      { "condition": "AND", "key": "suite", "operator": "=~", "value": "/^$suite$/" }
     ]
    }
   ]
  }
 ]
}